language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-trainline
    - secure: "jHhacVE25GoA8LbI29IXSF4dZNtpORQ5dgivVz3vnrd0mVlNFZHNd8Ny7CqR6ma9k90Xnsxa76jwDhb062y7EtQygUeQcryh/7rj2VGWFV77x5s/ldGLjlfFjhdmo8FTdctiHS21Q9xubBISWRSlQjVcrYCIKzqc5BAoaYUNIFo5pUkYjon2wPxUJr8G68PWEJeCqG5gnpzElXSoluW5MSPV9hQ8GgK8lYLztwoI+Ptmtye0PwiKxmgVlLNA+YJY1Fu6to3RKMvEqRdeB+BpaKVB8LuRlOjxrTuXaLwykF6yIWTqf+n7htlKpPp9WF3a8tfqeb2KCx/Au0/AfqMpLs6HIjH3RSWliiAogII3to0njG8B7+XqMAOYhhpYQLH/MdJ0PUmhixZ7tFo2EiikZ//hgd3xs80oCNk2aXMUhkhBzU/JSQKTtPQ83k7Zgs+CYDtOX0NBeWBAsON1KlcdIdE5+ofQpmRmYGGH8BMI+LDdHRngxcPDqnWITQu7wbp9akCGYDG3izjlG2haHU9zZ651uBhK2AMQEW20X74YlLtMJJL3b+KGu2OFQ0Vdbcit30s/YnSJc050gaEIySZyOU8VcOb0kyo7JWDZTD7cny5KeAkB0pnb45nDLJ7mUg6FbLkp5JWmDf2TBd0DFmZcT7AO6mUM9epwh7zuX1ebi28="
    # REGISTRY_TOKEN
    # to generate : travis encrypt REGISTRY_TOKEN=<your_REGISTRY_TOKEN> -r konnectors/cozy-konnector-trainline
    - secure: "C2Ko8x9bVZhqIiYWqkJHxwsodRwvj5TZpYNP6BMfFffCFcuNBDm9e7kdgVuhfSU6DdmTx74OtoUPrw6MZnmJXYgQwMsTopGTLMsgIACHR/9/oGn3qenbPHwYjDLlP44EQHut74Io/xudbVkHGelk0RrxjcYkChGpXnH8CIpZtDhN9mdZ0Ii0TyGLyEhzG+jA/6rLZfv1mQqggiQn43LY4hWIw9lcA6PIkwCDblNCjeKairIdnafJsXuB26unsKqJiiwbVxCJClLhp9DZvN6UfiNH83nzTj9bz/v+pjSYMsIC8deOFejOL2ivhSZXIc77CjkUeopLN0yrxpagLycxakVUhbzaiyynesOQHf+sySpin5pq3KglefLOEy5vEn2EgJNiYiVTnrHwUYwyzQOvVWhsZT5ET0FVjfteIs4ZCsgbFSU+C7xZb3sOB7MwkVLVUeDqBGx9SdPLe/Cv/vSM4RXUlb98GhR9ng2n880F8GJ7iEPDxLNBE98ocOWZ9tiO2C+/3K3DAlaBIka21L0/1wYC0Rjq+QCTctkJDIZYXx9/sDM3WJK2pEf/fQ9iEF0FeuXncoBzI1ybNA1b7gFEgihisHFaYfrisPx+ChHdYVz1Lq0FBBsKLSgtD305mK5OhEoa5dR5TXUIXfb4yGggLmmLNU4Z73s+WGooKYJkcrQ="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-trainline
    skip-cleanup: true
    script: yarn deploy && TRAVIS_COMMIT=$(git rev-parse build) yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-trainline
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy && TRAVIS_COMMIT=$(git rev-parse latest) yarn cozyPublish
    on:
      branch: prod
